# 使用例子，请根据实际情况修改

description = "Command Line Tool"
[arguments]
diseases = { required = true, default = "我是一个自定义值", type = "str", help = "要查找的疾病/症状名称" }
db_type = { choices = ["direct", "all"], help = "数据库类型(direct/all)" }